# Generated by Django 5.0 on 2023-12-30 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_alter_post_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='short_body',
            field=models.CharField(default='', max_length=100),
        ),
    ]
