# Generated by Django 5.0 on 2023-12-30 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='short_body',
        ),
    ]
