# Generated by Django 5.0.1 on 2024-01-02 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_profile_status'),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChatModel',
            new_name='ChatMessage',
        ),
        migrations.RenameIndex(
            model_name='chatmessage',
            new_name='chat_chatme_sent_at_661952_idx',
            old_name='chat_chatmo_sent_at_54a4be_idx',
        ),
    ]
